del  hkust-beamer.aux
del  hkust-beamer.bbl
del  hkust-beamer.blg
del  hkust-beamer.log
del  hkust-beamer.nav
del  hkust-beamer.out
del  hkust-beamer.run.xml
del  hkust-beamer.snm
del  hkust-beamer.synctex.*
del  hkust-beamer.toc
del  hkust-beamer-blx.bib